# language: node_js

services:
  - docker

before_install:
  - docker pull node:9

install:
  - docker build -t dbs-scrapper .

script:
  - docker run --name scrapper -v ${TRAVIS_BUILD_DIR}:/home/node/app/web-page/build dbs-scrapper yarn build

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_OAUTH_TOKEN
    keep-history: false
    varbose: true
    on:
      branch: gh-pages
      